[DEFAULT]
#Ruta de escritura de los indicadores (String)
outPath=/var/www/html/observatorioboyaca/
#outPath=C:/xampp/htdocs/website/

#Email de soporte
senderEmail=observatorios.boyaca@gmail.com
password=xmakcbczyjjoxoss
receiverEmail=dontor@gmail.com

#Habilitación de envío de archivos procesados al repositorio
git=true

#Archivo de escritura de logs y errores (String)
logFile=looper.log

#Detalle de log (Entero)
#0:  NOTSET
#10: DEBUG
#20: INFO
#30: WARN
#40: ERROR
#50: CRITICAL
logVerbosity=20

#Formato de log (String)
#logFormat=

#Tiempo de inactividad en segundos (Entero)
sleepTime=10